### ISSUE TITLE
How To Disable Render value in some chart

### ISSUE THREAD

**Issue by zeraferrari** [emn178/Chart.PieceLabel.js#145]
Sir, how to disable render value in some chart ? i want another my chart not display render value, what must i do ? in documentation value render property not have value disable, or false

**Comment by SoyDiego** [comment]
Hi @zeraferrari , do you have the solution for this?
I show all the renders in my graphics but i want show only in one piechart.
I added the code only in the config of my piechart but its shown in all my graphics. How could you solved it? 
Thanks!

**Comment by SoyDiego** [comment]
The solution is:

```        
plugins: {
 labels: false,
},

```
:)
