### ISSUE TITLE
Use Chart PieceLabel with angular 2 or higher project

### ISSUE THREAD

**Issue by kingkassem** [emn178/Chart.PieceLabel.js#15]
how to include this with an angular 2 project

**Comment by kingkassem** [comment]
i include it's in the script , and work fine

thanks alot for this great job

Best Regards

**Comment by dhniels** [comment]
What do you mean include it in the script? can you show  me how you got it working? Im using angular2-chart.js

**Comment by dhniels** [comment]
nevermind, i was able to figure it out. see #17
