### ISSUE TITLE
not working with angular2-chart.js

### ISSUE THREAD

**Issue by dhniels** [emn178/Chart.PieceLabel.js#17]
not working for me when using the angular2-chart.js package. am i missing something? i tried installing via npm, and added this to my component.ts doughnut chart options:

```
pieceLabel: {
     mode: 'percentage',
     precision: 1,
}
```

**Comment by dhniels** [comment]
Finally figured this out. I had to include it in my app.module.ts file like so:
`const PieceLabel = require('chart.piecelabel.js');`

normally in angular you would do something like `import {PieceLabel} from 'chart.piecelabel.js';` but it requires that the author create an `@types/chart.piecelabel.js`

anyway, hopefully other people using this in angular2-chart.js will see this and get it working :)

Oh, and dont forget to define it in your systemjs config file. i believe that is required to make it work as well.

**Comment by kingkassem** [comment]
what i did is
install it 
open  angular-cli.json  
in scripts section add 
"../node_modules/chart.piecelabel.js/build/Chart.PieceLabel.min.js",
i think it must be below chat.js like this
        "../node_modules/chart.js/dist/Chart.bundle.min.js",
        "../node_modules/chart.piecelabel.js/build/Chart.PieceLabel.min.js",
and it works with me
Best Regards,

**Comment by pantonis** [comment]
@kingkassem I have 
```
"../node_modules/chart.js/dist/chart.js",
"../node_modules/chart.piecelabel.js/src/Chart.PieceLabel.js"     
```
and in my component 
```
import 'Chart.PieceLabel.js';
```

```
pieceLabel: {
                render: 'value'
            }
```
but I don't see any label
