### ISSUE TITLE
Multiple pieceLabel on the same doughnut ?

### ISSUE THREAD

**Issue by ianonthenet** [emn178/Chart.PieceLabel.js#18]
First, thank you for your nice plugin.

Now, question : **Is it possible to have 2 pieceLabel option on the same doughnut ?**
example:
![doughnut](https://user-images.githubusercontent.com/12033474/28170743-91f0e63c-67e6-11e7-875a-2a49019ddb91.jpg)

percentage inside
```
  pieceLabel: {
    mode: 'percentage'
  }
```
and labels outside
```
  pieceLabel: {
    mode: 'label',
    fontColor: '#000',
    position: 'outside'
  }
```

**Comment by emn178** [comment]
It has no this feature now. Maybe we can add in the future.

**Comment by suyalcinkaya** [comment]
+1

**Comment by jryd** [comment]
+1

**Comment by SeanLMcCullough** [comment]
You could probably render an invisible dataset with the labels you want with rgba(0,0,0,0) set for the colors.

**Comment by Seb33300** [comment]
+1

I think you should set a pieceLabels param to accept multiple labels:

``` javascript
pieceLabels: {
    {
        mode: 'percentage'
    },
    {
        mode: 'label',
        fontColor: '#000',
        position: 'outside'
    }
}
```

**Comment by emn178** [comment]
v0.14.0 supports this feature. please try it.

**Comment by Seb33300** [comment]
I am waiting for npm to get the latest version but it's still on v0.13.0: https://www.npmjs.com/package/chart.piecelabel.js

Do you have a way to force NPM to update?

**Comment by emn178** [comment]
forget to publish, please try again

**Comment by Seb33300** [comment]
Working for me:
![image](https://user-images.githubusercontent.com/915273/43954613-5ac7cf6a-9cc7-11e8-8de5-a320b636e51a.png)

Not related to this issue, but as you can see on the screenshot, outside arc labels are not perfectly centered.
Also, % seems to be very close of the number.

**Comment by emn178** [comment]
@Seb33300 please open an new issue, and provide your config.
