### ISSUE TITLE
place text on the border

### ISSUE THREAD

**Issue by skyporter** [emn178/Chart.PieceLabel.js#2]
To prevent long text not displaying it could be nice if there is an option to place the text in the border of the chart.
<img width="445" alt="capture d ecran 2017-03-22 a 11 06 54" src="https://cloud.githubusercontent.com/assets/417818/24192751/4c70d44a-0ef0-11e7-8b59-b4befe88014c.png">

**Comment by emn178** [comment]
Ok, I'll try this when I have time.

**Comment by emn178** [comment]
this feature has added in v0.3.0. you can try it.

**Comment by skyporter** [comment]
thank you very much ! It works like a charme.
