### ISSUE TITLE
label-parameter in format-function

### ISSUE THREAD

**Issue by modanch** [emn178/Chart.PieceLabel.js#21]
Please add a label-parameter in format-function like this:

value = this.format(value, chartInstance.config.data.labels[i]);

Gives more posibilties for formatting the text. Thx.

**Comment by emn178** [comment]
you mean something like this?
```JavaScript
      format: function (value, label) { 
        return label + ': ' + value;
      }
```

**Comment by emn178** [comment]
you can use render function to do this in v0.7.0.
