### ISSUE TITLE
Value sometimes doesn't render well

### ISSUE THREAD

**Issue by cesartl** [emn178/Chart.PieceLabel.js#25]
See below:

![piecelabel](https://user-images.githubusercontent.com/18382796/28787159-5121ca46-7613-11e7-84f6-a73f05022e0f.gif)

Does it happen if the number would't fit?

My config:

```
pieceLabel: {
    mode: this.state.piePercentage ? 'percentage' : 'value',
    precision: 0,
    fontColor: '#333333',
    fontStyle: 'bold',
    format: (v) => {
        return `${symbol}${v.format(0, 3, ',')}`;
    }
}
```

**Comment by emn178** [comment]
it tries to avoid overlap so that it can't show if string is too long.

**Comment by cesartl** [comment]
Would it be possible to have an option to turn this off in case we always want to show the value? Or would you have another idea?

**Comment by emn178** [comment]
v0.7.0 add overlap option to configure this. please try it.

**Comment by cesartl** [comment]
Excellent !!
