### ISSUE TITLE
Filter Issue

### ISSUE THREAD

**Issue by jwhulette** [emn178/Chart.PieceLabel.js#27]
When filtering data, it's not applying the label to all sections of the graph.
![dashboard](https://user-images.githubusercontent.com/4930051/29418947-c9738c0c-833b-11e7-99db-b360cc93dcdc.png)

**Comment by emn178** [comment]
I think text is too long to display. try to set `overlap: true`. see if it's too long.

**Comment by jwhulette** [comment]
That was it. Thanks!
