### ISSUE TITLE
fontColor as function

### ISSUE THREAD

**Issue by Hintalo** [emn178/Chart.PieceLabel.js#29]
Hi,
currently the fontColor of the texts can be a single color or an array of color-values. It would be nice if we could provide also a function (callback) that will be called automatically, with all needed parameters about the current text/dataset/label, incl. the current backgroundColor. Then the callback could decide itself, which color should be used for that text, ex. it could compute the brightness of the current pie slice (according to the backgroundColor) and decide between "white" and "black" dynamically.
I have implemented this feature in my fork and added a pull-request. It contains also an own example in the demo-page. Can you please have a look at it?
Thanks,
Cheers,
Peter

**Comment by emn178** [comment]
ok, I will check. thanks.

**Comment by emn178** [comment]
added this feature into v0.8.0

**Comment by Hintalo** [comment]
Cool, thanks!
