### ISSUE TITLE
How to render label+value in different line

### ISSUE THREAD

**Issue by ethanlinys** [emn178/Chart.PieceLabel.js#31]
How to render label+value in different line.
like below:
 CRITICAL
     100

MAJOR
    99

**Comment by emn178** [comment]
It doesn't support multiple lines.

**Comment by marqmarti** [comment]
+1

**Comment by jeherrera** [comment]
I was looking in to this and have a hacky version working for a project I'm doing - you can substitute this in on line 161 of the unminified version **IF** you only have one line break. I spent some time trying to expand it to accommodate any number of newlines, but for some reason the chart wasn't playing nice with my for-loop. I might investigate more later, but here it is:

```
//this might need to check for any other line break as well, like \r
var split_string = text.split('\n');
//writes the first line of your label string to the canvas
this.fillText(split_string[0], position, fontColor);
if(split_string.length>1){
    //new_pos slides the write position down by the size of your font so there's no overlap
    new_pos = {
        x: position.x,
	y: position.y+(this.fontSize)
    };
    //writes the second line of your label string to the canvas, below the first
    this.fillText(split_string[1], new_pos, fontColor);
}
```
Here's the forloop I was testing out if someone can spot some egregious error I just plain missed:
```
for(i=0;i<split_string.length;i++){
    var new_pos = {
        x: position.x,
 	y: position.y+(i*this.fontSize)
    };
    this.fillText(split_string[i], new_pos, fontColor);
}
```
Its still pretty rough, I'm sure there's logic you could add to completely render and center _n_ lines of text. Let me know if this helps at all or there are any questions.

**Comment by emn178** [comment]
I will check this when I have time.

**Comment by jigsdatta** [comment]
I have used the piecelable to place the label. But my labels size is bigger so half ( or small portion ) of the label is hiding under the chart slice. You can check this below image:

![donught](https://user-images.githubusercontent.com/6175613/33363152-27aed284-d505-11e7-862a-6ea3526d7808.png)

Can anyone please suggest how can I solve this issue?

**Comment by pommierw** [comment]
Based on @jeherrera trick and tested on 0.8.2 version, just need to replace the fillText prototype method with below :

```javascript
PieceLabel.prototype.fillText = function (text, position, fontColor) {
      var ctx = this.ctx;
      if (typeof text === 'object') {
        ctx.drawImage(text, position.x - text.width / 2, position.y - text.height / 2, text.width, text.height);
      } else {
        ctx.fillStyle = fontColor;
        ctx.textBaseline = 'top';
        ctx.textAlign = 'center';
        var split_string = text.split('\n');
        for(var i=0;i<split_string.length;i++){
          var new_pos = {
            x: position.x,
            y: (position.y - this.fontSize / 2) + (i*this.fontSize)
          };
          ctx.fillText(split_string[i], new_pos.x, new_pos.y);
        }
      }
    };
```

Example in your chart options :

```javascript
pieceLabel: {
    render: function (args) {
        return args.label + '\n' + args.value;
    }
}
```

or simply add "\n" in your data labels or datasets ;)

**Comment by aztekinetix** [comment]
+1

**Comment by ziagiseldina** [comment]
Hi guys!
@pommierw says he just need to replace the fillText prototype method but how? Where is it?


> Based on @jeherrera trick and tested on 0.8.2 version, just need to replace the fillText prototype method with below :
> 
> PieceLabel.prototype.fillText = function (text, position, fontColor) {
>       var ctx = this.ctx;
>       if (typeof text === 'object') {
>         ctx.drawImage(text, position.x - text.width / 2, position.y - text.height / 2, text.width, text.height);
>       } else {
>         ctx.fillStyle = fontColor;
>         ctx.textBaseline = 'top';
>         ctx.textAlign = 'center';
>         var split_string = text.split('\n');
>         for(var i=0;i<split_string.length;i++){
>           var new_pos = {
>             x: position.x,
>             y: (position.y - this.fontSize / 2) + (i*this.fontSize)
>           };
>           ctx.fillText(split_string[i], new_pos.x, new_pos.y);
>         }
>       }
>     };
> Example in your chart options :
> 
> pieceLabel: {
>     render: function (args) {
>         return args.label + '\n' + args.value;
>     }
> }
> or simply add "\n" in your data labels or datasets ;)

**Comment by emn178** [comment]
v0.13.0 support this feature. please try it.
