### ISSUE TITLE
Add modules example in README.md

### ISSUE THREAD

**Issue by StanislavMayorov** [emn178/Chart.PieceLabel.js#34]
Hi. Thank you for the plugin. 
Please add examples how it can be used with commonJS and es6 modules.

**Comment by emn178** [comment]
it should be
```JavaScript
require('chart.piecelabel.js');
```
or
```JavaScript
import 'chart.piecelabel.js'
```

**Comment by StanislavMayorov** [comment]
I know. I thought it could be usefull in the plugin description.
