### ISSUE TITLE
Percentage render format

### ISSUE THREAD

**Issue by suyalcinkaya** [emn178/Chart.PieceLabel.js#36]
First of all thank you, it's really useful. All I'm wondering is when using percentage render, it just round off the number. I mean if the percentage is 20.66, it shown as just 21. It may not be related to this but do you know any solution to fix it?

```js
...,
pieceLabel: {
    render: 'percentage',
    fontColor: '#fff',
    overlap: true
},
...,
```

![chart](https://user-images.githubusercontent.com/16385367/31667085-0cda877a-b357-11e7-93cf-da125942ccba.PNG)

**Comment by emn178** [comment]
option precision
https://github.com/emn178/Chart.PieceLabel.js#usage  
https://emn178.github.io/Chart.PieceLabel.js/samples/demo/

**Comment by suyalcinkaya** [comment]
Wow. I missed that bad :sweat_smile: Thanks.
