### ISSUE TITLE
Is it possible to add background image behind doughnut chart or center of doughnut chart

### ISSUE THREAD

**Issue by MohamedSahir** [emn178/Chart.PieceLabel.js#40]
I have an requirement to show the gif animation behind doughnut chart which will occupy the center as well as doughnut chart not beyond the doughnut chart? is it possible to use by chart js as well as Chart.PieceLabel.js in angular4 component. 

And one more thing is one value will be as 25 means slight orange,50 means little dark orange , if value reaches 75 means much more darker orange , how to achieve is it possible?

**Comment by emn178** [comment]
1. just use `<img>` or `background-image` and set a proper position under canvas element.
2. calculate backgroundColor by your value before assigning datasets.

**Comment by MohamedSahir** [comment]
can you provide some peice of code to draw the image behind donut  , I don't how to start this.

Here is  the question i have asked in stackoverflow
`
https://stackoverflow.com/questions/47269631/is-it-possible-to-add-image-behind-doughnut-chart-with-transparency-color-in-ng2`

**Comment by emn178** [comment]
use rgba backgroundColor
https://jsfiddle.net/33jfrc1L/
