### ISSUE TITLE
Not all Lables are rendered

### ISSUE THREAD

**Issue by EMFHDinf** [emn178/Chart.PieceLabel.js#41]
Hi emn178,

first of all thank you for this handy extension to chartjs.
It works with ease and the fontColor function of your example is a nice way to dynamically determine the font color!

But sadly it doesn't render all values properly in my example:

![image](https://user-images.githubusercontent.com/2171919/32733621-11febdc2-c890-11e7-9cd8-4c1be0139a9f.png)

My definition is:
           pieceLabel: {
                render: 'percentage',
                fontColor: function (data) {
                    var rgb = rgbStringToObject(data.dataset.backgroundColor[data.index]);
                    var threshold = 140;
                    var luminance = 0.299 * rgb.r + 0.587 * rgb.g + 0.114 * rgb.b;
                    return luminance > threshold ? 'black' : 'white';
                },
                precision: 0
            }

The Chartsize is only 272 * 175 pixels (including the legend and title).
I think, they don't render because there is not enough space.
You got any idea on it or is there any code/configuration enhancement i could go for or could you give me a hint how to remove the fitting check?

Thank you very much in advance.

P.S.: it will display all labels with, but sadly that's not the requirement ;)
        pieceLabel: {
            render: 'percentage',
            **fontColor: 'black',**
            precision: 0,
            **position: 'outside',**
        }
![image](https://user-images.githubusercontent.com/2171919/32734248-bec99a08-c891-11e7-81bd-623065a36db2.png)

**Comment by EMFHDinf** [comment]
okay, now I got only 1 Missing value:
![image](https://user-images.githubusercontent.com/2171919/32735850-21e7351a-c896-11e7-818a-08b9f2bffa49.png)

I added **position: 'border'** to the configuration to get the result above.

But still i would love to have all values displayed ;)
advise is kindly requested.

**Comment by emn178** [comment]
```
overlap: true
```
I need to add FAQ.

**Comment by EMFHDinf** [comment]
Thank you very much :) works with ease!
