### ISSUE TITLE
Bigger label rendering issue

### ISSUE THREAD

**Issue by jigsdatta** [emn178/Chart.PieceLabel.js#45]
I have used the piecelable to place the label. But my labels size is bigger so half ( or small portion ) of the label is hiding under the chart slice. You can check this below image:

![donught](https://user-images.githubusercontent.com/6175613/33363272-bd332c6a-d505-11e7-9c76-9e49be5be20b.png)

Can anyone please suggest how can I solve this issue?

**Comment by emn178** [comment]
Use different font color for now?

**Comment by jigsdatta** [comment]
If I use different font color then it will be overlap on the chart slice. But I don't want it in that way. So if you can suggest any other way or fix this in the next version then it will be helpful.

**Comment by jalleng** [comment]
Has there been any update on this issue?  We are experiencing the same problem.

**Comment by jrobichaux** [comment]
I was able to fix this problem by adjusting the position.x value in the drawDataset function. In this part of the function (at line 112 of version 0.11.0):

        if (this.position === 'outside') {
          if (position.x < view.x) {
            position.x -= offset;
          } else {
            position.x += offset;
          }
          arcOffset = view.outerRadius + offset;
        }

I adjusted the **offset** to account for the width of the label. So now it looks like this:

        if (this.position === 'outside') {
          offset += (this.measureText(text).width / 2);
          if (position.x < view.x) {
            position.x -= offset;
          } else {
            position.x += offset;
          }
          arcOffset = view.outerRadius + offset;
        }

**Comment by jrobichaux** [comment]
code above is added in pull request #61
