### ISSUE TITLE
align label "right" inside a piece/sector

### ISSUE THREAD

**Issue by martinmetsalu** [emn178/Chart.PieceLabel.js#49]
Inside a piece/sector would it be possible to position the label on the "right" side?

![piecelabel-alignment](https://user-images.githubusercontent.com/2835874/35913226-a9812f30-0c07-11e8-93d4-ff2910feca37.png)

**Comment by romulus001** [comment]
Hello, don't you mean on the border? if so, put `position:"border"` in the options

**Comment by martinmetsalu** [comment]
Hello, I tried `position: "border"` but for unknown reasons the label is still center aligned. I also tried `position: "outside"` which did work. Here is my configuration:

```
var params = {
  display: true,
  text: "%l",
  color: "white",
  borderWidth: 0,
  lineWidth: 0,
  padding: 3,
  textAlign: "center",
  stretch: 15,
  backgroundColor: "",
  lineColor: "rgba(255, 255, 255, 0)",
  font: {
    size: 24,
    resizable: true,
    minSize: 14,
    maxSize: 18
  }
}

var myChart = new Chart(ctx, {
  type: 'outlabeledDoughnut',
  data: {
    labels: 
    [
      "Label 1",
      "Label 2",
    ],
    datasets: [{
      data: [12, 13],
      backgroundColor: [
      'rgba(17, 234, 175, 1)', // 1
      'rgba(251, 95, 98, 1)',  // 2
      ],
      borderColor: 'rgba(26, 43, 70, 1)',
      borderWidth: 3,
    }]
  },
  options: {
    responsive: true,
    maintainAspectRatio: false,
    cutoutPercentage: 33.33,
    zoomOutPercentage: 25,
    tooltips: {
      enabled: false
    },
    plugins: {
      legend: false,
      title: false,
      outlabels: params
    },
    pieceLabel: {
      render: "percentage",
      fontColor: "white",
      fontSize: 14,
      precision: 0,
      showZero: true,
      overlap: false,
      //arc: true,
      position: "border"
    },
  }
});
```

**Comment by romulus001** [comment]
maybe it's cause of the presence of the option `responsive: true`, I can't really say more as myself, I don't manage to correctly use this component, maybe it's because of compatibility prob

**Comment by martinmetsalu** [comment]
yes, looks like a compatibility issue. I got it working with "pie" but not "doughnut" chart: 

```
var myChart = new Chart(ctx, {
  type: 'pie',
  data: {
    datasets: [{
      data: [31,59],
      backgroundColor: [
      'rgba(17, 234, 175, 1)', // 1
      'rgba(251, 95, 98, 2)',  // 2
      ],
      borderColor: 'rgba(26, 43, 70, 1)',
      borderWidth: 5,
    }]
  },
  options: {
    responsive: true,
    maintainAspectRatio: false,
    cutoutPercentage: 33.33,
    legend: {
      display: false
    },
    tooltips: {
      enabled: false
    },
    zoomOutPercentage: 0,
    plugins: {
      outlabels: false
    },
    pieceLabel: {
      render: 'percentage',
      fontColor: 'white',
      fontSize: 14,
      precision: 0,
      showZero: true,
      position: "border",
    },
  }
});
```
And when I use **chartjs-plugin-piechart-outlabels** plugins "outlabeledPie" or "outlabeledDoughnut" options it also center aligns the label.

**Comment by emn178** [comment]
`position: 'border'` only work when `type == 'pie'`
https://github.com/emn178/Chart.PieceLabel.js/blob/master/src/Chart.PieceLabel.js#L99
I thought `border` has no effect in doughnut chart, so skip it for performance. Try this if it works
```JavaScript
        this.position === 'border') {
```

**Comment by martinmetsalu** [comment]
I removed `&& chartInstance.config.type === 'pie'` and it works.

**Comment by emn178** [comment]
ok, I will remove this in next version if it has no other issue.

**Comment by martinmetsalu** [comment]
Thank you for your help. What do you think, should I notify the author of piechart-outlabels plugin? There might be more users out there who would like to use both plugins together.
