### ISSUE TITLE
Publish 0.2.0 version to npm

### ISSUE THREAD

**Issue by VyTacka** [emn178/Chart.PieceLabel.js#5]
Thank you for this plugin 👍 

I've installed this plugin using Yarn and just noticed that I'm using an older version (0.1.0).
So I tried to upgrade it but Yarn still installed the old version so I assume that you forgot to do `npm publish` because as I can see in https://www.npmjs.com/package/chart.piecelabel.js it still shows that the latest package version is 0.1.0 😉 

You can find more info about updating npm packages here - 
https://docs.npmjs.com/getting-started/publishing-npm-packages#updating-the-package

Thanks!

**Comment by emn178** [comment]
forgot to publish. thanks.
