### ISSUE TITLE
Condition in Custom render

### ISSUE THREAD

**Issue by SteNil123** [emn178/Chart.PieceLabel.js#53]
Is it possible to have condition on the custom render?

When using this code it will not show any labels at all.
If the Pie has a lot of small pieces it will be nice to choose to not show them.

`pieceLabel: {
            render: function (args) {
                if (args.percentage > 5) 
                    return args.label;
            },
            fontColor: '#000',
            position: 'outside',
            segment: true
}`

**Comment by emn178** [comment]
Please upgrade to v0.10.0, and you can try something like below.
```JavaScript
render: function (args) {
  if (args.percentage < 1) {
    return '';
  } else {
    return args.label;
  }
}
```
