### ISSUE TITLE
Cannot read property 'afterDatasetsDraw' of undefined

### ISSUE THREAD

**Issue by Pennstater** [emn178/Chart.PieceLabel.js#60]
Using Angular 5, PrimeNG and ChartJS 2.7.2.  Multiple charts loaded fine **before** adding PieceLabel. After adding, receive the error: Cannot read property 'afterDatasetsDraw' of undefined.  I believe "undefined" in this case is the actual chart object (chart.pieceLabel.* or a.pieceLabel.* in the minified code).

*component.ts loads the PieceLabel minified JS file in the "ngAfterViewInit" lifecycle event. The constructor of this component creates the charts (there are multiple charts on a page, each rendered in a *ngFor loop).

Here is a sample (not all elements shown) of the chart object defined in the constructor (hopefully this formats correctly - GitHub keeps reminding me my browser is no longer supported (using Chrome through my company which is several versions behind))...

```
this.gauges = [
  {
    name: 'chart1',
    type: 'pie',
    data: {
      datasets: [
        {
          data: [100, 200, 100]
        }
      ]
    },
    options: {
      pieceLabel: {
        render: 'value',
        position: 'outside'
      }
    }
  }
]
```

(Imagine a couple of more charts added to the "this.gauges" object.)

The PieceLabel JS is being loaded and appears to be registered to the charts. The charts start rendering but stop just as the rendering animation starts (so you see a little bit of the charts on the screen). Then Chrome shows the error in the console.

Within the minified code, the error occurs on this line...

afterDatasetsDraw: function (a) { a.pieceLabel.afterDatasetsDraw(a) }

Thanks.

**Comment by emn178** [comment]
You should load Chart.PieceLabel.js before chart component load.
If you use this library with angular2-chartjs, you can import after angular2-chartjs
```
import { ChartModule } from 'angular2-chartjs';
import 'chart.piecelabel.js';
```
