### ISSUE TITLE
Labels missing in production build

### ISSUE THREAD

**Issue by petarGitNik** [emn178/Chart.PieceLabel.js#64]
Hi, I'm using angular 6+ (with angular cli), and when I make a production build of my projects labels are missing, and there is not any warning in the console about (labels are present as long as I don't use `--prod`).

First, I've imported it in `main.ts`, but I also tried to import it after ng2-charts in `app.module.ts` as suggested on issue #47 :

```js
import { ChartsModule } from 'ng2-charts';
import 'chart.piecelabel.js';
```

But that didn't work also. I've also added it in `angular.json` configuration file as:

```json
"scripts": [
  "./node_modules/chart.js/dist/Chart.bundle.min.js",
  "./node_modules/chart.piecelabel.js/build/Chart.PieceLabel.min.js"
]
```

But that does not have any effect  also.

**Comment by emn178** [comment]
what version are you using?

**Comment by petarGitNik** [comment]
@emn178  Here are the version of the relevant libraries including the plugin:

```json
"chart.piecelabel.js": "^0.12.0",
"ng2-charts": "^1.6.0",
"@angular/cli": "^6.0.8",
```

**Comment by emn178** [comment]
I try your env, but I can't reproduce your issue. please provide more info or sample project.

**Comment by petarGitNik** [comment]
I've made a sample project that you can clone from [here][1] and start with `ng serve --prod`. The supposed bug is also present with the "0.14.1" version of the plugin. Alternatively, you can view the live version on [stackblitz][2] (live version is in development mode).

I basically fetch the data from the API, and display it in pie charts. User can change between pie charts using a dropdown menu.

[1]: https://github.com/petarGitNik/chromium-chart-js-bug
[2]: https://stackblitz.com/github/petarGitNik/chromium-chart-js-bug

**Comment by steinv** [comment]
@petarGitNik 
Using your demo I was able to get the labels, while serving as production, by rearranging the imports.

In `app.module.ts`
remove the chart.piecelabel.js import

In `pie.component.ts`
add import for chart js and chart piecelabel js:
`// Import chart js and chartpiecelabel in order
import 'chart.js';
import 'chart.piecelabel.js';`

**Comment by petarGitNik** [comment]
@steinv Thanks! It works!  However, I use only

```javascript
import 'chart.piecelabel.js';
```

In my `pie.component.ts`, I do not have to `import 'chart.js'`. Would importing of chart.js conflict with ng2-charts?

**Comment by steinv** [comment]
Don't know if it conflicts.
I had the a similar issue a while back. 
This is how I had solved it.

**Comment by emn178** [comment]
This issue is caused by import Chart.js twice and there are two Chart different instances.
one chart.js from angular.json and the other one from import 'chart.js'

remove chart.js in angular.json and set up `app.module.ts`
```TypeScript
import { ChartsModule } from 'ng2-charts';
import 'chart.js';
import 'chart.piecelabel.js';
```
