### ISSUE TITLE
Draw label outside chart

### ISSUE THREAD

**Issue by woutrbe** [emn178/Chart.PieceLabel.js#8]
Is it possible to add an option to draw the label outside the chart?

<img width="215" alt="screen shot 2017-04-27 at 5 49 04 pm" src="https://cloud.githubusercontent.com/assets/1826229/25477944/d490cf40-2b71-11e7-84c2-6db811197a96.png">

**Comment by emn178** [comment]
I will try this when I have time.

**Comment by emn178** [comment]
Hi, this feature added in v0.4.0. You can try it.

**Comment by woutrbe** [comment]
That looks great @emn178 and was exactly what I was looking for. Thanks!
